### ISSUE TITLE
Code review for vivekscl

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W13-B1/main#115]
![image](https://user-images.githubusercontent.com/1023494/32639662-e4708350-c5ff-11e7-84ec-ea8587b2a0df.png)
- In the above, header comments do not follow the norm we suggest
- try to avoid arrow head code if you can

![image](https://user-images.githubusercontent.com/1023494/32639706-0f2414ae-c600-11e7-813f-001cd6c78390.png)
- In the above, it is a "comment" not a "header comment" :stuck_out_tongue: 
- Same issue in : /java/seedu/address/ui/MainWindow.java `setWindowUserDefinedSize`

**Comment by okkhoy** [comment]
@vivekscl fya

**Comment by vivekscl** [comment]
For the first error, I'm not sure if this is the norm suggested for the header comment. Refactored to remove arrow head code as well.
![deepinscreenshot_select-area_20171110110947](https://user-images.githubusercontent.com/17037188/32641228-c401effc-c607-11e7-9059-fe62dc43f0b3.png)


For the second error, is this what you mean by header comment?
![deepinscreenshot_select-area_20171110105316](https://user-images.githubusercontent.com/17037188/32640815-762fa456-c605-11e7-88de-34051fff83f8.png)

**Comment by vivekscl** [comment]
Changed the`getClosestMatchingNameForMultipleKeywords` to use Java streams:
![deepinscreenshot_select-area_20171110113045](https://user-images.githubusercontent.com/17037188/32641767-bdc5090a-c60a-11e7-9ea0-1bd26602b6c7.png)

**Comment by vivekscl** [comment]
Action has been taken to refactor code.
