### ISSUE TITLE
code quality comments for taojiashu

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-W13-B1/main#118]
![image](https://user-images.githubusercontent.com/1023494/32640279-ea96366e-c602-11e7-822f-417a331a51a7.png)
- can try to split these to new lines for better readability

![image](https://user-images.githubusercontent.com/1023494/32640307-05e79016-c603-11e7-9d02-dfd1eda88e8d.png)
![image](https://user-images.githubusercontent.com/1023494/32640314-0e7928f2-c603-11e7-95c2-370da050b4d1.png)
![image](https://user-images.githubusercontent.com/1023494/32640337-2ae97ad2-c603-11e7-8483-cf378dfb9180.png)
- in all above, header comments don't follow the convention that we specify

@taojiashu fya

**Comment by taojiashu** [comment]
Do you mean that I need to use third person singular like 'Lists', 'Marks' and 'Displays'? Because in `LocateCommand`, I used the header comment of `ListCommand`
